### ISSUE TITLE
Visual bug when refreshing abilities in multiplayer

### ISSUE THREAD

**Issue by DreyerChris** [helcomsecretariat/ecosfera-baltica-digital#109]
Steps to reproduce:

- Use abilities on all players
- Buy 2 animals that share habitat

After the ability has been refreshed, the other ability tiles move from the stage to the players who are not currently active

**Comment by H1D** [comment]
@H1D 
 - single ability bug
 - abilities turn blue as soon as player have two animals (to soon)
