### ISSUE TITLE
Make it clear which player is next

### ISSUE THREAD

**Issue by DreyerChris** [helcomsecretariat/ecosfera-baltica-digital#112]
From the play test it seemed like the players did not find it easy to understand which player is next. This is important to know before refreshing a market or ending a turn.

**Comment by H1D** [comment]
@edwin-dmello-reaktor maybe use next player's name on a button?

**Comment by H1D** [comment]
wont do cuz of this. Should be obvious now
https://github.com/helcomsecretariat/ecosfera-baltica-digital/issues/121
