### ISSUE TITLE
Redesign end turn button

### ISSUE THREAD

**Issue by DreyerChris** [helcomsecretariat/ecosfera-baltica-digital#113]
It was not clear for the players in the play test how to end the turn. The end turn and refresh ability icons look very similar and causes confusion

**Comment by edwin-dmello-reaktor** [comment]
https://www.figma.com/design/Oa3LZc4sFdX6MiUQ3vCcuL/Design?node-id=737-8662&t=1rS4h1yQmaLcxgAa-4
