### ISSUE TITLE
Show exhausted cards more clearly

### ISSUE THREAD

**Issue by DreyerChris** [helcomsecretariat/ecosfera-baltica-digital#115]
Feedback from the playtest was that it was not clear that the exhausted cards are exhausted. Simply moving them to the side does not seem enough to indicate that they are out of play. Some considerations for an updated design:

- It is still important for players to be able to see the habitats of exhausted cards
- It is still important for players to be able to see and use the abilities of exhausted cards

In general the card hierarchy should be looked at

**Comment by H1D** [comment]
@edwin-dmello-reaktor, an overall observation: all the cards on the screen currently appear equally important, which doesn’t reflect their actual hierarchy. Would be better if UI will convey a logical structure, highlighting certain elements over others. For example, exhausted cards should appear much less prominent than active ones.

**Comment by edwin-dmello-reaktor** [comment]
https://www.figma.com/design/Oa3LZc4sFdX6MiUQ3vCcuL/Design?node-id=697-7712&t=1rS4h1yQmaLcxgAa-4
