### ISSUE TITLE
Re-think the icons of the abilities

### ISSUE THREAD

**Issue by DreyerChris** [helcomsecretariat/ecosfera-baltica-digital#118]
Feedback from the playtest was that the icons of the abilities were not clear because they seemed to be actions that affect the turn state of the game more than anything else. These icons do not look like they are meant to affect your cards. The suggestion here is to try out new icons with cards on them to make it clear that these actions affect your cards or the cards in the market

**Comment by H1D** [comment]
@edwin-dmello-reaktor maybe use shape of a card instead of circle?

<img width="1722" alt="image" src="https://github.com/user-attachments/assets/2be3846c-5e73-4481-ba0f-834eef04e9a2">

**Comment by H1D** [comment]
wont do
