### ISSUE TITLE
"No buy" punishment with exp. pack.

### ISSUE THREAD

**Issue by H1D** [helcomsecretariat/ecosfera-baltica-digital#186]
Current logic doesn't take into account buying via exp. pack cards.

1. Have a clean turn with no prior actions
2. Activate `Migratory barrier removal` 
3. Buy a card and move it (to some other player for fun)
4. end the turn

**Expected:** game proceeds to the next player without any punishment
**Actual:** current player gets "no  buy" punishment

---

Suggestion: lets use some shared "action" for that. We could have a simple file with actions for buying card like we do for guards and just invoke them from exp. pack cards logic.

**Comment by DreyerChris** [comment]
I think we will have to confirm this with Jannica, imo moving a card from the market to another player's hand should not count as "buying" if it wasn't moved to the player's own hand

**Comment by DreyerChris** [comment]
Confirmed by Jannica that this is not needed:

<img width="824" alt="Image" src="https://github.com/user-attachments/assets/4611a1a0-5bf3-47b1-81da-650a2f984cbc" />
