### ISSUE TITLE
Design basic layout

### ISSUE THREAD

**Issue by H1D** [helcomsecretariat/ecosfera-baltica-digital#2]
Creating a basic layout with all of the elements. The goal is to have all of the elements needed to play the game on the screen. This can then be an input for the developers.

Will NOT include any concepts, interactions, hover states, game mechanics or multiplayer.

**Definition of Done:**
  - basic layout is considered "approved" from the team for including all of the elements.

**Comment by i-j-r** [comment]
![Image](https://github.com/user-attachments/assets/ae5c4ff8-c3df-4b13-b5ca-41a8cf4850af)
