### ISSUE TITLE
Exhausted cards text offset

### ISSUE THREAD

**Issue by DreyerChris** [helcomsecretariat/ecosfera-baltica-digital#203]
When cards are exhausted, they are overlayed on top of each other and moved down, but the text on some card names get pushed off to the left and also overlays on top of cards to the right

**Comment by H1D** [comment]
@DreyerChris we should have a constant for total card thickness and rely on that everywhere when card are layed on top of each other facing up. 

The only caveat it to enforce that limit here somewhow... https://github.com/helcomsecretariat/ecosfera-baltica-digital/blob/4ac6629cf72a6b5148bc72a49dca09323f31ed85/src/components/Card.tsx#L37-L48
