### ISSUE TITLE
Automated deployment

### ISSUE THREAD

**Issue by H1D** [helcomsecretariat/ecosfera-baltica-digital#5]
Set up github CI/CD so we can easily deploy the game.

**Definition of Done:**

  - code pushed to github repo gets checked automatically (code lint, test runs) and deployed via Netlify integration

**Comment by H1D** [comment]
prod URL (updated manually) - https://ecosfera.netlify.app/

staging URL https://main--ecosfera.netlify.app/

https://github.com/helcomsecretariat/ecosfera-baltica-digital/commit/0d54b2f6509bc22ed5c04ceae00d87c618b000db

**Comment by i-j-r** [comment]
Mostly configured on Netlify side but here are some configs - https://github.com/helcomsecretariat/ecosfera-baltica-digital/blob/main/netlify.toml
